tags: Add new tag to advertise the use of BCP-003-03
AMWA-TV/nmos-parameter-registers pull request #20
Opened 2020-10-14 14:17 UTC by JamesGibo

See https://github.com/AMWA-TV/nmos-certificate-provisioning/pull/7
for more information

2020-10-29 09:32 UTC, garethsb-sony requested changes
Thanks, James, looks good.

2020-10-29 09:32 UTC, garethsb-sony commented on tags/certprov.md
> +- **Name:**  urn:x-nmos:tag:certpro
```suggestion
- **Name:**  urn:x-nmos:tag:certprov
```

2020-10-29 09:32 UTC, garethsb-sony commented on tags/certprov.md
> +JSON tags for when BCP-003-03 is NOT being used to automatically provision TLS certificates or is not supported
Perhaps we should characterize this as "implemented but disabled", since if it's simply not supported, it's more likely that the tag would be omitted completely?

```suggestion
#### 3. BCP-003-03 implemented but disabled

JSON tags for when BCP-003-03 is supported but NOT currently being used to automatically provision TLS certificates
```

2020-10-29 10:02 UTC, garethsb-sony commented on tags/certprov.md
> +| enabled version | A string that defines what version of BCP-003-03 is enabled | Version string "v{major}.{minor}", eg. "v1.0" |
```suggestion
| enabled version | A string that defines what version of BCP-003-03 is enabled | Version string "v{major}.{minor}", e.g. "v1.0" |
```

2020-10-29 11:15 UTC, garethsb-sony approved these changes

2020-10-29 13:45 UTC, andrewbonney approved these changes

2020-10-29 13:46 UTC, andrewbonney commented
Does it make sense to wait to merge this until BCP-003-03 is complete to avoid unnecessary changes to a live document?

2020-10-29 13:47 UTC, garethsb-sony commented
> Does it make sense to wait to merge this until BCP-003-03 is complete to avoid unnecessary changes to a live document?

Yes, I think so.

2020-10-29 13:49 UTC, peterbrightwell commented
Yes I think so

From: Andrew Bonney <notifications@github.com>
Reply to: AMWA-TV/nmos-parameter-registers <reply@reply.github.com>
Date: Thursday, 29 October 2020 at 13:46
To: AMWA-TV/nmos-parameter-registers <nmos-parameter-registers@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Subject: Re: [AMWA-TV/nmos-parameter-registers] tags: Add new tag to advertise the use of BCP-003-03 (#20)


Does it make sense to wait to merge this until BCP-003-03 is complete to avoid unnecessary changes to a live document?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://github.com/AMWA-TV/nmos-parameter-registers/pull/20#issuecomment-718763365>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ADV4FSDIIJVCHMNPCQSETSTSNFW4FANCNFSM4SQVR3PQ>.

2020-11-02 10:08 UTC, cristian-recoseanu commented on tags/certprov.md
> +#### 2. BCP-003-03 disbaled
Typo for "disabled" here

2021-04-08 14:01 UTC, merged